### PR TITLE
post new users to database, styled movie cards, added name input field

### PR DESCRIPTION
**Pull request by tylerjhevia**
Fixed post user action, added hover state and appearing text to movie cards, added an input field for name

### CODE REVIEW

**Comment by jackmallahan** [comment]
sweet action

**Comment by jackmallahan** [comment]
Lets not have any more type-os

**Comment by jackmallahan** [comment]
typos?

**Comment by jackmallahan** [comment]
type-o

**Comment by jbexx** [comment]
killer hover states Tyler.  They're super sweet.  Lets work on that p tag opacity on the movie card.  otherwise,  nice work on the, but watch the type-Os

**Pull request merged**
